### ISSUE TITLE
Plugin not working with Sketch 52.1

### ISSUE THREAD

**Issue by daverobsonvb** [mheesakkers/sketch-plugin-skew#1]
Great plugin, have used it a lot! Unfortunately, however, since upgrading to Sketch 52 the plugin no longer does anything after selecting the skew degree and clicking 'ok'...

**Comment by mheesakkers** [comment]
Thanks for letting me know! I'm currently figuring out how to fix this. Seems the internal workings of Sketch have changed. I hope to fix this as soon as possible.

**Comment by mheesakkers** [comment]
@daverobsonvb if all went well you were asked to update the plugin and it should be working again. Could you please let me know if it works? Thanks!

**Comment by daverobsonvb** [comment]
Ah perfect! Yes, had an update available to v1.1 which is now working as expected again! Thanks for sorting that so quickly, this is such a useful plugin.
