### ISSUE TITLE
Skewing to 30 degrees not working

### ISSUE THREAD

**Issue by daverobsonvb** [mheesakkers/sketch-plugin-skew#2]
Hi again,

I've just been using the plugin after you were able to get it working in Sketch 52, and have noticed that it doesn't seem to be skewing to 30 degrees correctly (I've only tried 30 and 45, but 45 degrees seems ok).

I've attached a file comparing a Sketch shape skewed to 30 degrees using your plugin, a bitmap of a shape skewed to 30 degrees in Photoshop and then pasted in to Sketch, and finally a single line drawn in Sketch and rotated to 30 degrees.

The Photoshop shape and the Sketch lines match their angles but, unfortunately, the shaped skewed to 30 degrees via the plugin doesn't match the other two in the finished angle for some reason?

Not sure if this is related to the Sketch 52 compatibility issue or not, so have raised it as a new issue.

Thanks

![sketch skew plugin error](https://user-images.githubusercontent.com/28566074/46731260-2302c900-cc82-11e8-952e-93e6e37a89cc.jpg)

**Comment by daverobsonvb** [comment]
I've realised that this issue is because the orange shape in Sketch was rectangular. When I try skewing a square shape with the Skew! plugin it matches the other methods of skewing/rotating shapes and lines.

However, surely the degree the shape is skewed by shouldn't differ by the original shape - surely the angle after it's skewed should always match the requested angle when running the plugin...?

**Comment by mheesakkers** [comment]
Hi @daverobsonvb thanks for letting me know! This is a known issue and I still need to figure out how to get it exactly right. I'll add to the to do!

**Comment by mheesakkers** [comment]
Hi @daverobsonvb I think I've got some good news for you. I looked into the skewing math and I think I figured out a solution ;) Please try it out and let me know if it works.

**Comment by daverobsonvb** [comment]
@mheesakkers That's great, yes seems to be all working as expected and generating the correct angles every time no matter what the original ratio etc! Thanks again for getting this sorted so swiftly!
