### ISSUE TITLE
Plugin not working with Sketch 53.1

### ISSUE THREAD

**Issue by moqu79** [mheesakkers/sketch-plugin-skew#3]
It's a great plugin!
While the plugin no longer does anything after selecting the skew degree and press the "OK" button.

**Comment by mheesakkers** [comment]
Thanks! Just came across this myself. It seems that there were some changes in the API. I will look into this as soon as possible!

**Comment by mheesakkers** [comment]
@moqu79 if all went well you should get a notification of Sketch to update the Skew plugin which will work in Sketch 53.1. Could you please check and let me know if all works as expected?

**Comment by moqu79** [comment]
@mheesakkers Hi bro, it's working perfectly as expected again, thanks!
